- name: deploy my_lambda_function
  hosts: local
  vars:
    aws_region: cn-northwest-1
    s3_bucket: my-lambda-bucket
    code_path: my_lambda_function/
    zip_name: my_lambda_function.zip
    email_address: boxing.peng@thermofisher.com
  vars_files:
    - aws_credentials.yaml
    - tags.yaml
  environment:
    AWS_ACCESS_KEY_ID: '{{ dscops.AWS_ACCESS_KEY_ID }}'
    AWS_SECRET_ACCESS_KEY: '{{ dscops.AWS_SECRET_ACCESS_KEY }}'
  tasks:
    - include: includes/init_workspace.yml
    - include: includes/build_zip.yml
    - include: includes/copy_to_s3.yml

    - name: cloudformation stack
      amazon.aws.cloudformation:
        region: '{{ aws_region }}'
        stack_name: my-lambda-function
        template: files/my_lambda_function_stack.yml
        template_format: yaml
        template_parameters:
          S3Bucket: '{{ s3_bucket }}'
          S3Key: '{{ zip_name }}'
          S3ObjectVersion: '{{ s3_version_id }}'
          Email: '{{ email_address }}'
        tags:
          '{{ aws_tags }}'
