- name: deploy my_lambda_function
  hosts: local
  gather_facts: yes
  vars:
    aws_region: cn-northwest-1
    s3_bucket: my-lambda-bucket
    git_repo: git@github.com:BoxingP/aws-lambda-python-function.git
    zip_name: my_lambda_function.zip
    email_address: boxing.peng@thermofisher.com
    virtualenv: '{{ hostvars[inventory_hostname].ansible_env.HOME }}/.virtualenvs/ansible-python-lambda-env'
    cron_schedule: 'cron(0 1-10/9 ? * MON-FRI *)'  #UTC
    schedule_description: 'Weekdays at 0900 and 1800'
  vars_files:
    - aws_credentials.yaml
    - tags.yaml
    - sudo_passwords.yaml
  environment:
    AWS_ACCESS_KEY_ID: '{{ dscops.aws_access_key_id }}'
    AWS_SECRET_ACCESS_KEY: '{{ dscops.aws_secret_access_key }}'
  tasks:
    - include_tasks: includes/init_environment.yml
    - include_tasks: includes/init_workspace.yml
    - include_tasks: includes/build_zip.yml
    - name: build aws environment
      block:
        - include_tasks: includes/copy_to_s3.yml
        - include_tasks: includes/create_cloudformation_stack.yml
      vars:
        ansible_python_interpreter: '{{ virtualenv }}/bin/python3'
