- name: deploy my_lambda_function
  hosts: local
  gather_facts: yes
  vars:
    aws_region: cn-northwest-1
    s3_bucket: my-lambda-bucket
    code_path: my_lambda_function/
    zip_name: my_lambda_function.zip
    email_address: boxing.peng@thermofisher.com
    virtualenv_home: '{{ hostvars[inventory_hostname].ansible_env.HOME }}/.virtualenvs'
    virtualenv: '{{ virtualenv_home }}/ansible-python-lambda-env'
  vars_files:
    - aws_credentials.yaml
    - tags.yaml
    - sudo_passwords.yaml
  environment:
    AWS_ACCESS_KEY_ID: '{{ dscops.aws_access_key_id }}'
    AWS_SECRET_ACCESS_KEY: '{{ dscops.aws_secret_access_key }}'
  tasks:
    - include: includes/init_environment.yml
    - include: includes/init_workspace.yml
    - include: includes/build_zip.yml
    - include: includes/copy_to_s3.yml
      vars:
        ansible_python_interpreter: '{{ virtualenv }}/bin/python3'
    - include: includes/create_cloudformation_stack.yml
      vars:
        ansible_python_interpreter: '{{ virtualenv }}/bin/python3'
