- name: find the s3 version we just uploaded
  command: >
    aws s3api head-object
      --region {{ aws_region }}
      --bucket {{ s3_bucket_name }}
      --key {{ s3_object_name }}
  register: head_object_output

- name: set s3_object_version_id
  set_fact:
    s3_object_version_id: '{{ (head_object_output.stdout|from_json)["VersionId"] }}'
