- name: git checkout codes
  git:
    repo: '{{ git_repo }}'
    depth: 1
    version: master
    dest: '{{ git_checkout_directory }}'
    force: yes
    accept_hostkey: yes

- name: find files to delete
  find:
    paths: '{{ git_checkout_directory }}'
    file_type: any
    hidden: yes
    excludes:
      - '{{ lambda_function_name }}.py'
      - 'requirements.txt'
  register: found_files

- name: delete useless files
  include_role:
    name: remove_file
  vars:
    file_to_remove: '{{ item.path }}'
  with_items:
    "{{ found_files['files'] }}"
