- name: remove any old zip
  file:
    path: "{{vars[ 'abs_' + build_directory + '_path' ]}}/{{ zip_name }}"
    state: absent

- name: zip files
  community.general.archive:
    path: "{{vars[ 'abs_' + files_need_to_zip_directory + '_path' ]}}/*"
    dest: "{{vars[ 'abs_' + build_directory + '_path' ]}}/{{ zip_name }}"
    format: zip
