- name: create the initial virtualenv
  pip:
    requirements: "{{vars[ 'abs_' + python_requirements_file_directory + '_path' ]}}/requirements.txt"
    virtualenv: '{{ virtualenv }}'
    virtualenv_command: /usr/bin/python3 -m venv