- name: generate cloudformation template
  template:
    src: ../templates/lambda_function_stack.j2
    dest: '{{ cloudformation_template }}'
    force: yes

- name: create cloudformation stack
  amazon.aws.cloudformation:
    region: '{{ aws_region }}'
    stack_name: '{{ cloudformation_stack_name }}'
    template: '{{ cloudformation_template }}'
    template_parameters:
      '{{ cloudformation_template_parameters }}'
    tags:
      '{{ cloudformation_tags }}'
